DELETE FROM CONFERENCE_ROOM_DETAILS;

INSERT INTO CONFERENCE_ROOM_DETAILS (ID,NAME, CAPACITY,CREATED_DATE) VALUES (1,'Amaze',3,NOW());
INSERT INTO CONFERENCE_ROOM_DETAILS (ID,NAME, CAPACITY,CREATED_DATE) VALUES (2,'Beauty',7,NOW());
INSERT INTO CONFERENCE_ROOM_DETAILS (ID,NAME, CAPACITY,CREATED_DATE) VALUES (3,'Inspire',12,NOW());
INSERT INTO CONFERENCE_ROOM_DETAILS (ID,NAME, CAPACITY,CREATED_DATE) VALUES (4,'Strive',20,NOW());