server:
  port: 8080
  servlet:
    application-display-name: conference-booking-service
    
    
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
maintenance:
    timings:
      - startTime: "09:00"
        endTime: "09:15"
      - startTime: "13:00"
        endTime: "13:15"
      - startTime: "17:00"
        endTime: "17:15"